name: publish

on:
  push:
    tags:
      - "v*"

jobs:
  pack-and-publish:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Extract version from tag
        id: get_version
        shell: bash
        run: |
          ref="${GITHUB_REF##*/}"
          ver="${ref#v}"
          echo "version=$ver" >> $GITHUB_OUTPUT

      - name: Restore
        run: dotnet restore Jaywapp.Wpf.csproj

      - name: Pack
        run: dotnet pack Jaywapp.Wpf.csproj -c Release -o nupkg /p:Version=${{ steps.get_version.outputs.version }}

      - name: List packages
        shell: pwsh
        run: |
          if (Test-Path nupkg) { Get-ChildItem -Recurse -File nupkg | ForEach-Object { Write-Host $_.FullName } } else { Write-Host "nupkg folder not found" }

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        shell: pwsh
        run: |
          $pkg = Get-ChildItem -Recurse -File nupkg -Filter *.nupkg | Select-Object -First 1
          if (-not $pkg) { Write-Error "No .nupkg found under nupkg/"; exit 1 }
          dotnet nuget push "$($pkg.FullName)" --api-key "$env:NUGET_API_KEY" --source https://api.nuget.org/v3/index.json --skip-duplicate

